apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-duckdns
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-duckdns
      namespace: {{ .Release.Namespace }}
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
  encryptedData:
    token: AgAURbOlxaKzFqqvi2jYtSg2qspSju0GsmTu4KoOh1HBa/Skt+yWYJY/omEBxpq7n/ble9xJza8vXvDI1Rn2cxpM6aTzaT6aUy+fZ7+QIQsLp5B/SKATYDAZvp8MDc2UhmxP8xJUVzo+Y5ScDRLGxubmoXV+o44naUg4dx/Ye6D96Bn3rJb+obyvDxTV77bBa40zsBLwAWZ9+fS+1n56zIRd1RtA0eSBOvZ2NAelUxRx+Xy99RJMPvik+RqLpoh4GIlXseQbh19X2WO/NOPYzxyMUd1f0YbelY1hPtmdXg0+z/IeQU02YGWa1cCRfnMR/S116zyARDeibs99yFeDgq29eR0ZRwD+lZ16ulyCZy7QAu39AYCcoOF8k8poSw4sMHnCz9TuXPWnWN0I31fAm/BEjCu455+2Ad1ZdsyHGD+1zBP5LKDk0p75Gmm1lTJmg7JbmpxjskoQf8ADczBEfscNNjANrAn327MDfz4umQAufVCPwVlkZTdQVIiv9UEC/0bZzOMS5uvhMPyJ6gqONH+CyGcNVaLDOtAcRZ6OR4mwLrKHVmyS91448drVAi/Tmw1VNp5eMYc1vhWqDmsEdhTUu2ylTp4VJLk/NWcNFAnU/u7+QAW/Zr8jrV1SbYUDSHA3+DzvrQp44hfQGugDHIRo61FBjWI7v0mQshej/88fh2BQU5syjtIQBLA8b/6O0Sn3OCSxtylTP6X6WBA2KQ4qAvwlbhD7X9aXAqjuOPUAxnMDFIk=
