apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Release.Name }}-duckdns
  namespace: {{ .Release.Namespace }}
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-duckdns
      namespace: {{ .Release.Namespace }}
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
  encryptedData:
    token: AgA/3fVIogU6YpeVS5zyfGYmJ+utfCX6dB2ZQmyRjPfyptv0RPVBRn7sUnKdIZtYr8K3lr8ZfyYSxA3+fe86ME4AolA6AJ+e7WYoDME9P2ry21GK0A6BYUy+7o/eTFcA8fv7NefPRTg/gKME9ehbSUUdp8a639QnJRvn157j0k1yWenxyhwXmwPDpxf6UGztX57K4YpP9ZOCHwPznMSisaVY5lp02jnS/HfE0wCF4TMiScPPf5JKF8tgLLAhGdglpX5D3UxE6n+QucS56j+qUuc/u0syqUCDHjTBhkdMYiXhNwGBA4fvcjs6028EmdXguSNDdvq3OXWUuXU56ODOAPwV1k2k3XEwd1PIK1pII0yPe0lkAuEWTHQExuUf/i9L4X0gBQrbU7ALSAP+DaaqbCTP0vTzkxgvQZbBp6OSqg4c/SNOtZUAsFtPRBJ+6yZ/LW99wdCMLOb8ApN5+iy1oPlOUhUfA88Dfn8u3yhREqbwFWDxnKP+pqbHC1KEhL27AhwRJUAyXfsipiQoq/zCdZjCsewp0JWqTAil3JWFoSW88BASmmO1DPDx8bUoxsc/ueHDNIxSbyMUSyAVnfrUz7lqChulkQ27JgG69GKetfmmovf/eAYAeRATrIm6DXq8wxIbnA6xugaKj9kru8kwTakxDYkJDocJsdZ9MTIUPALIEdZMynFp0xPmV5Ykx2C0aAjETMW285Vzg1cfWAkDf0i4sFdHhIf46p5ZzcHYVUk7mIkaJxs=
