{{- if .Values.argocd.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: {{ .Release.Namespace }}
spec:
  project: default
  source:
    repoURL: ghcr.io
    chart: argoproj/argo-helm/argo-cd
    targetRevision: {{ .Values.argocd.targetRevision }}
    {{- if .Values.argocd.valuesObject }}
    helm:
      valuesObject:
        {{- .Values.argocd.valuesObject | toYaml | nindent 8 }}
    {{- end }}
  destination:
    namespace: argocd
    server: {{ .Values.server }}
{{- end }}
