{{- if .Values.jellyfin.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: {{ .Release.Namespace }}
spec:
  project: default
  source:
    repoURL: https://jellyfin.github.io/jellyfin-helm
    chart: jellyfin
    targetRevision: {{ .Values.jellyfin.targetRevision }}
    {{- if .Values.jellyfin.valuesObject }}
    helm:
      valuesObject:
        {{- .Values.jellyfin.valuesObject | toYaml | nindent 8 }}
    {{- end }}
  destination:
    namespace: jellyfin
    server: {{ .Values.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
