{{- if .Values.sealedSecrets.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealedsecrets
  namespace: {{ .Release.Namespace }}
spec:
  project: default
  source:
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    chart: sealed-secrets
    targetRevision: {{ .Values.sealedSecrets.targetRevision }}
    helm:
      valuesObject:
        fullnameOverride: sealed-secrets-controller
        {{- if .Values.sealedSecrets.valuesObject }}
        {{- .Values.sealedSecrets.valuesObject | toYaml | nindent 8 }}
        {{- end }}
  destination:
    namespace: kube-system
    server: {{ .Values.server }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}
