apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: minecraft
      port: 25565
      targetPort: 25565
      nodePort: {{ .Values.service.nodePort }}
  type: NodePort
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
