server: https://kubernetes.default.svc

argocd:
  enabled: true
  targetRevision: 7.4.1
  valuesObject:
    global:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
    repoServer:
      env:
        - name: ARGOCD_GIT_MODULES_ENABLED
          value: "false"

metricsServer:
  enabled: true
  targetRevision: 3.12.1
  valuesObject:
    args:
      - --kubelet-insecure-tls
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

homeAssistant:
  enabled: true
  targetRevision: 0.2.71
  valuesObject:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

sealedSecrets:
  enabled: true
  targetRevision: 2.16.1
  valuesObject:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

ddns:
  enabled: true
  valuesObject:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

localPathStorage:
  enabled: true
  targetRevision: 0.0.28
  valuesObject:
    nodePathMap:
      - node: DEFAULT_PATH_FOR_NON_LISTED_NODES
        paths:
          - /var/local-path-provisioner
    storageClass:
      defaultClass: true
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

minecraft:
  enabled: true
