server: https://kubernetes.default.svc

argocd:
  enabled: true
  targetRevision: 7.4.1
  valuesObject:
    global:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          effect: NoSchedule
    repoServer:
      env:
        - name: ARGOCD_GIT_MODULES_ENABLED
          value: "false"

metricsServer:
  enabled: true
  targetRevision: 3.12.1
  valuesObject:
    args:
      - --kubelet-insecure-tls
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule

homeAssistant:
  enabled: true
  targetRevision: 0.2.71
  valuesObject:
    tolerations:
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
